package com.example.utils

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Environment
import android.util.Log
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.model.AttendanceRecord
import com.example.data.model.AttendanceSession
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfExporter {

    /**
     * Simulates exporting attendance session records to a structured PDF report document 
     * and triggers the native OS Share Intent.
     */
    fun shareSessionReport(
        context: Context,
        session: AttendanceSession,
        records: List<AttendanceRecord>
    ) {
        try {
            val simpleDateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
            val dateStr = simpleDateFormat.format(Date(session.createdAt))
            
            // Generate a beautifully structured textual/CSV report document
            val reportTitle = "ATTENDANCE_REPORT_${session.courseCode}_${session.id}"
            val file = File(context.cacheDir, "$reportTitle.txt")
            
            val writer = FileOutputStream(file)
            val sb = StringBuilder()
            
            sb.append("====================================================\n")
            sb.append("        UNIVERSITY ACADEMIC ATTENDANCE REPORT       \n")
            sb.append("====================================================\n\n")
            sb.append("Course Code:     ${session.courseCode}\n")
            sb.append("Course Title:    ${session.courseTitle}\n")
            sb.append("Lecturer Name:   ${session.lecturerName}\n")
            sb.append("Session Date:    $dateStr\n")
            sb.append("Status:          ${session.status}\n")
            sb.append("Geofence Radius: ${session.radiusMeters} meters\n")
            sb.append("Coordinates:     Lat: ${session.latitude}, Lon: ${session.longitude}\n\n")
            
            sb.append("Present Student Enlisted:\n")
            sb.append("---------------------------------------------------------------------------------------------------\n")
            sb.append(String.format("%-15s | %-25s | %-18s | %-12s | %-15s\n", "REG NO", "STUDENT NAME", "CHECK-IN TIME", "DISTANCE (m)", "STATUS"))
            sb.append("---------------------------------------------------------------------------------------------------\n")
            
            if (records.isEmpty()) {
                sb.append("No student checked in for this attendance session.\n")
            } else {
                for (rec in records) {
                    val arrivalTime = SimpleDateFormat("HH:mm:ss", Locale.getDefault()).format(Date(rec.timestamp))
                    sb.append(
                        String.format(
                            "%-15s | %-25s | %-18s | %-12s | %-15s\n",
                            rec.registerNo,
                            rec.studentName,
                            arrivalTime,
                            String.format("%.1f", rec.distanceMeters),
                            rec.status
                        )
                    )
                }
            }
            sb.append("---------------------------------------------------------------------------------------------------\n\n")
            sb.append("Generated on: ${simpleDateFormat.format(Date())}\n")
            sb.append("Generated by: Smart Attendance System Mobile Client\n")
            sb.append("====================================================\n")
            
            writer.write(sb.toString().toByteArray())
            writer.close()

            // Safe file sharing via FileProvider
            val authority = "${context.packageName}.fileprovider"
            val uri: Uri = FileProvider.getUriForFile(context, authority, file)
            
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "Attendance Report - ${session.courseCode}")
                putExtra(Intent.EXTRA_TEXT, "Hello, here's the exported academic attendance roster report for ${session.courseCode}.")
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            
            context.startActivity(Intent.createChooser(intent, "Export & Share Attendance Report"))
        } catch (e: Exception) {
            Log.e("PdfExporter", "Error exporting: ${e.message}")
            Toast.makeText(context, "Error compiling report: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }
}
